### ISSUE TITLE
https://www.pccc.com/downloads/SpamAssassin/contrib/KAM.cf not working

### ISSUE THREAD

**Issue by nutellinoit** [lucascbeyeler/zimbra#12]
The url is unreachable

**Comment by lucascbeyeler** [comment]
Hello @nutellinoit ,

I'm going to check if there is a new link for the SaKAM file and change later.

Thanks for your report.

Regards,
Lucas Costa Beyeler

**Comment by nutellinoit** [comment]
Thank you!

**Comment by nutellinoit** [comment]
Seems that the link is back online

**Comment by lucascbeyeler** [comment]
Welp, closing the bug report =/
