### ISSUE TITLE
fix for config

### ISSUE THREAD

**Issue by kruisdraad** [lucascbeyeler/zimbra#14]
Hey, 

nice work on latest version. There is a bug though. The config item has changed into:

mailboxd_truststore="/opt/zimbra/common/lib/jvm/openjdk-11.0.2-zimbra/lib/security/cacerts"

**Comment by FlorianHeigl** [comment]
Here I got 

```
zimbra@zimbra:~$ ls /opt/zimbra/common/lib/jvm/openjdk-1.8.0_172-zimbra/lib/
amd64  ct.sym  dt.jar  ir.idl  jconsole.jar  jexec  orb.idl  sa-jdi.jar  tools.jar
```

the cacerts paths are:
```
zimbra@zimbra:~$ find . -name cacerts
./common/lib/jvm/openjdk-1.8.0_172-zimbra/jre/lib/security/cacerts
./common/etc/java/cacerts
```
I searched for files named ```*.jks``` but found none. Uncertain if it's a problem or just the wrong file name.

this is with 8.8 on Ubuntu 16 (sigh)

**Comment by lucascbeyeler** [comment]
Fixed the issue - it's working normally with 8.8.15 now and only with 8.8.15.

I decided to drop the other versions to make easier for me to maintain the code.

**Comment by darlinho** [comment]
> Ici j'ai
> 
> ```
> zimbra@zimbra:~$ ls /opt/zimbra/common/lib/jvm/openjdk-1.8.0_172-zimbra/lib/
> amd64  ct.sym  dt.jar  ir.idl  jconsole.jar  jexec  orb.idl  sa-jdi.jar  tools.jar
> ```
> 
> les chemins des cacerts sont:
> 
> ```
> zimbra@zimbra:~$ find . -name cacerts
> ./common/lib/jvm/openjdk-1.8.0_172-zimbra/jre/lib/security/cacerts
> ./common/etc/java/cacerts
> ```
> 
> J'ai recherché des fichiers nommés `*.jks`mais n'en ai trouvé aucun. Incertain s'il s'agit d'un problème ou simplement du mauvais nom de fichier.
> 
> Les certificats en amont purs semblent être installés et OK:
> 
> ```
>   1318524      0 lrwxrwxrwx   1 root     root           34 May 28  2018 ./common/lib/jvm/openjdk-1.8.0_172-zimbra/jre/lib/security/cacerts -> ../../../../../../etc/java/cacerts
>    798514    224 -rw-r--r--   1 zimbra   zimbra     229158 Mar  1 04:50 ./common/etc/java/cacerts
> ```
> 
> c'est avec 8.8 sur Ubuntu 16 (soupir)
> 
> # ÉDITER
> J'ai eu le même problème sur 8.8.15
> 
> ```
> root@xenial-vm1132:~# less /tmp/zmsetup.20200304-005627.log
> [...]
> Wed Mar  4 00:56:42 2020 *** Running as zimbra user: /opt/zimbra/bin/zmlocalconfig -f -e mailboxd_keystore_password='123change' 2> /dev/null
> Wed Mar  4 00:56:43 2020 Setting local config zimbra_ldap_userdn to uid=zimbra,cn=admins,cn=zimbra
> Wed Mar  4 00:56:43 2020 *** Running as zimbra user: /opt/zimbra/bin/zmlocalconfig -f -e zimbra_ldap_userdn='uid=zimbra,cn=admins,cn=zimbra' 2> /dev/null
> Wed Mar  4 00:56:43 2020 done.
> Wed Mar  4 00:56:43 2020 checking isEnabled zimbra-core
> Wed Mar  4 00:56:43 2020 zimbra-core is enabled
> Wed Mar  4 00:56:43 2020 Initializing core config...
> Wed Mar  4 00:56:43 2020 Setting up CA...
> Wed Mar  4 00:56:43 2020 *** Running as zimbra user: /opt/zimbra/bin/zmcertmgr createca -new
> ** Creating directory '/opt/zimbra/conf/ca'
> ** Creating directory '/opt/zimbra/ssl/zimbra'
> ** Creating directory '/opt/zimbra/ssl/zimbra/ca'
> ** Creating directory '/opt/zimbra/ssl/zimbra/commercial'
> ** Creating directory '/opt/zimbra/ssl/zimbra/server'
> ** Creating directory '/opt/zimbra/ssl/zimbra/ca/newcerts'
> ** Touching file '/opt/zimbra/ssl/.rnd'
> ** Touching file '/opt/zimbra/ssl/zimbra/ca/index.txt'
> ** Creating /opt/zimbra/ssl/zimbra/ca/zmssl.cnf
> ** Retrieving CA private key from LDAP... failed
> ** Creating CA with new private key /opt/zimbra/ssl/zimbra/ca/ca.key
> Generating a RSA private key
> ..................................................................+++++
> ..................................................................................+++++
> writing new private key to '/opt/zimbra/ssl/zimbra/ca/ca.key'
> -----
> Wed Mar  4 00:56:45 2020 done.
> Wed Mar  4 00:56:45 2020 Deploying CA to /opt/zimbra/conf/ca ...
> Wed Mar  4 00:56:45 2020 *** Running as zimbra user: /opt/zimbra/bin/zmcertmgr deployca -localonly
> ** Importing cert '/opt/zimbra/ssl/zimbra/ca/ca.pem' as 'my_ca' into cacerts '/opt/zimbra/common/lib/jvm/java/jre/lib/security/cacerts'
> ERROR: cacerts keytool(-import -alias my_ca -noprompt -file /opt/zimbra/ssl/zimbra/ca/ca.pem) returned non-zero(1):
> Certificate was added to keystore
> keytool error: java.io.FileNotFoundException: /opt/zimbra/common/lib/jvm/java/jre/lib/security/cacerts (No such file or directory)
> Wed Mar  4 00:56:46 2020 failed.
> ****
> ```
> 
> C'est ~ 8.8.15:
> 
> ```
> root@xenial-vm1132:~# ls -l /opt/zimbra/common/lib/jvm/openjdk-*/lib/security/cacerts
> lrwxrwxrwx 1 root root 31 Dec  4 11:36 /opt/zimbra/common/lib/jvm/openjdk-13.0.1-zimbra/lib/security/cacerts -> ../../../../../etc/java/cacerts
> ```

Hello please i have same problem how can i resolved it please

**Comment by lucascbeyeler** [comment]
Just use the latest version of the playbook. The error is happening only for the old version.
